"""Curated vendor asset templates with common endpoints pre-populated.

Each template contains realistic defaults. Users provide base_url + credentials,
and we instantiate an Asset + its Endpoints in one shot.
"""
from typing import List, Dict


TEMPLATES: List[Dict] = [
    {
        "id": "commvault",
        "vendor": "Commvault",
        "name": "Commvault Complete Backup & Recovery",
        "tagline": "Enterprise backup, recovery and archiving.",
        "description": "Commvault WebConsole REST API. Token-based auth via /login with Basic header, subsequent calls use 'Authtoken: QSDK <token>' header.",
        "auth_type": "token",
        "auth_hint": "Use your Commvault WebConsole credentials. The password should be base64-encoded. Login requires Authorization: Basic Og== header.",
        "auth_defaults": {
            "login_path": "/login",
            "login_method": "POST",
            "username_field": "username",
            "password_field": "password",
            "token_path": "token",
            "token_header": "Authtoken",
            "token_prefix": "",
            "login_headers": {
                "Authorization": "Basic Og==",
                "Accept": "application/json",
                "Content-Type": "application/json",
            },
        },
        "base_url_example": "https://commvault.example.com/webconsole/api",
        "color": "#E31B23",
        "endpoints": [
            # ── Clients ──
            {"name": "list_clients", "method": "GET", "path": "/Client",
             "description": "List all backup clients registered with the CommServe."},
            {"name": "get_client", "method": "GET", "path": "/Client/{clientId}",
             "description": "Get details of a specific client by clientId including connectivity status and installed agents."},
            {"name": "get_client_properties", "method": "GET", "path": "/Client/{clientId}/properties",
             "description": "Get full properties of a client: schedules, storage policies, network config, readiness status. Essential for RCA."},
            # ── Jobs (last 24h) ──
            {"name": "list_jobs", "method": "GET", "path": "/Job",
             "description": "List backup/restore jobs from the last 24 hours. Always pass completedJobLookupTime=86400 to limit to last 24h. Filter by status like 'failed' for RCA.",
             "query_params": [
                 {"name": "completedJobLookupTime", "description": "Seconds to look back for completed jobs. Use 86400 for last 24 hours. ALWAYS include this.", "required": False},
                 {"name": "status", "description": "Job status filter: pending, running, completed, failed, killed, etc.", "required": False},
                 {"name": "jobFilter", "description": "Filter e.g. 'activeJobs'", "required": False},
                 {"name": "clientId", "description": "Filter jobs by specific client ID", "required": False},
                 {"name": "subclientId", "description": "Filter jobs by specific subclient ID", "required": False},
             ]},
            {"name": "get_job", "method": "GET", "path": "/Job/{jobId}",
             "description": "Get details of a specific job by jobId including failure reason, error code, start/end time, bytes transferred."},
            # ── Events / Logs ──
            {"name": "get_events", "method": "GET", "path": "/Events",
             "description": "Get event viewer logs. Use jobId filter to find error events for a failed job. Critical for root cause analysis.",
             "query_params": [
                 {"name": "jobId", "description": "Filter events for a specific job ID.", "required": False},
                 {"name": "level", "description": "Event severity: 0=info, 2=warning, 4=error, 6=critical.", "required": False},
                 {"name": "showInfo", "description": "Set to false to hide info events.", "required": False},
                 {"name": "showMinor", "description": "Set to false to hide minor events.", "required": False},
             ]},
            # ── Alerts ──
            {"name": "get_alerts", "method": "GET", "path": "/AlertRule",
             "description": "List all configured alert rules and their trigger conditions."},
            {"name": "get_triggered_alerts", "method": "GET", "path": "/Alert",
             "description": "Get recently triggered alerts including severity, description, and affected entity. Useful for RCA."},
            # ── Subclients & Storage ──
            {"name": "list_subclients", "method": "GET", "path": "/Subclient",
             "description": "List subclients (logical data grouping) for backup policies.",
             "query_params": [
                 {"name": "clientId", "description": "Filter subclients by client ID.", "required": False},
             ]},
            {"name": "get_subclient", "method": "GET", "path": "/Subclient/{subclientId}",
             "description": "Get subclient details: content, storage policy, schedule, and last backup status."},
            {"name": "list_storage_policies", "method": "GET", "path": "/StoragePolicy",
             "description": "List all storage policies including copy precedence, retention rules, and associated media agents."},
            # ── Actions ──
            {"name": "start_backup", "method": "POST", "path": "/Subclient/{subclientId}/action/backup",
             "description": "Trigger an on-demand backup for the given subclient."},
        ],
    },
    {
        "id": "rubrik",
        "vendor": "Rubrik",
        "name": "Rubrik Security Cloud (RSC)",
        "tagline": "Immutable backups & ransomware recovery.",
        "description": "Rubrik Security Cloud (Polaris) GraphQL API. Uses client_id/client_secret for token auth via /api/client_token. All data queries use POST /api/graphql.",
        "auth_type": "token",
        "auth_hint": "Create a Service Account in RSC and provide the client_id and client_secret. Put client_id in the Username field and client_secret in the Password field.",
        "auth_defaults": {
            "login_path": "/api/client_token",
            "login_method": "POST",
            "login_body_fields": {
                "client_id": "{username}",
                "client_secret": "{password}",
            },
            "token_path": "access_token",
            "token_header": "Authorization",
            "token_prefix": "Bearer ",
        },
        "base_url_example": "https://your-org.my.rubrik.com",
        "color": "#00B2A9",
        "endpoints": [
            {"name": "backup_jobs", "method": "POST", "path": "/api/graphql",
             "description": "List recent backup activity/jobs via GraphQL.",
             "default_body": {"query": "query { activitySeriesConnection(filters: {lastActivityType: [BACKUP]}, sortBy: LAST_UPDATED, sortOrder: DESC, first: 20) { nodes { id objectName objectType lastActivityStatus lastActivityType startTime lastUpdated failureReason } } }"}},
            {"name": "threat_hunts", "method": "POST", "path": "/api/graphql",
             "description": "List threat hunt activities via GraphQL.",
             "default_body": {"query": "query { activitySeriesConnection(filters: {lastActivityType: [THREAT_HUNT]}, sortBy: LAST_UPDATED, sortOrder: DESC, first: 20) { nodes { activitySeriesId objectName objectType lastActivityStatus lastActivityType severity startTime lastUpdated failureReason } } }"}},
            {"name": "anomaly_events", "method": "POST", "path": "/api/graphql",
             "description": "List anomaly detection events via GraphQL.",
             "default_body": {"query": "query { activitySeriesConnection(filters: {lastActivityType: [ANOMALY]}, sortBy: LAST_UPDATED, sortOrder: DESC, first: 20) { nodes { id objectName objectType lastActivityStatus severity startTime lastUpdated } } }"}},
            {"name": "protected_objects", "method": "POST", "path": "/api/graphql",
             "description": "List protected objects/VMs via GraphQL.",
             "default_body": {"query": "query { snappableConnection(first: 20) { nodes { id name objectType slaDomain { name } protectionStatus lastSnapshot } } }"}},
            {"name": "cluster_info", "method": "POST", "path": "/api/graphql",
             "description": "Get Rubrik cluster information via GraphQL.",
             "default_body": {"query": "query { clusterConnection { nodes { id name status defaultAddress version } } }"}},
        ],
    },
    {
        "id": "netapp",
        "vendor": "NetApp",
        "name": "NetApp ONTAP REST API",
        "tagline": "Storage, data protection, and cluster management.",
        "description": "NetApp ONTAP 9.6+ REST API. Uses HTTP basic auth by default.",
        "auth_type": "basic",
        "auth_hint": "Use ONTAP admin credentials (e.g. 'admin' + password).",
        "auth_defaults": {},
        "base_url_example": "https://ontap.example.com/api",
        "color": "#0077C8",
        "endpoints": [
            {"name": "cluster_info", "method": "GET", "path": "/cluster",
             "description": "Get cluster identity, version, management IP."},
            {"name": "list_volumes", "method": "GET", "path": "/storage/volumes",
             "description": "List all volumes across SVMs.",
             "query_params": [
                 {"name": "svm.name", "description": "Filter by SVM name", "required": False},
                 {"name": "fields", "description": "Comma-separated fields e.g. 'size,space'", "required": False},
             ]},
            {"name": "get_volume", "method": "GET", "path": "/storage/volumes/{uuid}",
             "description": "Get a specific volume by UUID."},
            {"name": "list_svms", "method": "GET", "path": "/svm/svms",
             "description": "List Storage Virtual Machines (SVMs)."},
            {"name": "list_aggregates", "method": "GET", "path": "/storage/aggregates",
             "description": "List storage aggregates (physical disk pools)."},
            {"name": "list_snapshots", "method": "GET", "path": "/storage/volumes/{uuid}/snapshots",
             "description": "List snapshots for a given volume."},
        ],
    },
    {
        "id": "dell_powermax",
        "vendor": "Dell PowerMax",
        "name": "Dell PowerMax (Unisphere for PowerMax)",
        "tagline": "All-flash enterprise storage array.",
        "description": "Unisphere for PowerMax REST API. HTTP basic auth. Replace {version} with e.g. 100 for v10.0.",
        "auth_type": "basic",
        "auth_hint": "Use Unisphere admin credentials (smc user).",
        "auth_defaults": {},
        "base_url_example": "https://unisphere.example.com:8443/univmax/restapi",
        "color": "#007DB8",
        "endpoints": [
            {"name": "system_version", "method": "GET", "path": "/system/version",
             "description": "Get Unisphere & array firmware versions."},
            {"name": "list_arrays", "method": "GET", "path": "/100/sloprovisioning/symmetrix",
             "description": "List all managed PowerMax/VMAX arrays."},
            {"name": "list_storage_groups", "method": "GET", "path": "/100/sloprovisioning/symmetrix/{sid}/storagegroup",
             "description": "List storage groups on a specific array (sid = serial id)."},
            {"name": "get_storage_group", "method": "GET", "path": "/100/sloprovisioning/symmetrix/{sid}/storagegroup/{sg_name}",
             "description": "Get a specific storage group's details."},
            {"name": "list_volumes", "method": "GET", "path": "/100/sloprovisioning/symmetrix/{sid}/volume",
             "description": "List volumes on an array.",
             "query_params": [
                 {"name": "num_of_storage_groups", "description": "Filter volumes by SG count", "required": False},
             ]},
            {"name": "performance_array", "method": "GET", "path": "/performance/Array/metrics",
             "description": "Array-level performance metrics (IOPS, latency, throughput)."},
        ],
    },
    {
        "id": "veeam",
        "vendor": "Veeam",
        "name": "Veeam Backup & Replication",
        "tagline": "Modern data protection for virtual, physical & cloud.",
        "description": "Veeam Enterprise Manager / B&R REST API v1. OAuth2 bearer token via /api/oauth2/token.",
        "auth_type": "token",
        "auth_hint": "Token endpoint uses form-encoded grant_type=password. The default template expects a JSON login — adjust if your Veeam requires form auth.",
        "auth_defaults": {
            "login_path": "/api/oauth2/token",
            "login_method": "POST",
            "username_field": "username",
            "password_field": "password",
            "token_path": "access_token",
            "token_header": "Authorization",
            "token_prefix": "Bearer ",
        },
        "base_url_example": "https://veeam.example.com:9419",
        "color": "#00B336",
        "endpoints": [
            {"name": "list_jobs", "method": "GET", "path": "/api/v1/jobs",
             "description": "List all backup jobs with their state."},
            {"name": "list_backups", "method": "GET", "path": "/api/v1/backups",
             "description": "List backup files with retention and size."},
            {"name": "list_restore_points", "method": "GET", "path": "/api/v1/restorePoints",
             "description": "List available restore points."},
            {"name": "list_sessions", "method": "GET", "path": "/api/v1/sessions",
             "description": "List recent backup/restore sessions with status & duration."},
            {"name": "start_job", "method": "POST", "path": "/api/v1/jobs/{jobId}/start",
             "description": "Start a backup job immediately."},
        ],
    },
    {
        "id": "pure_storage",
        "vendor": "Pure Storage",
        "name": "Pure Storage FlashArray",
        "tagline": "All-flash storage with the Evergreen model.",
        "description": "Purity REST API v2.x. Token-based — POST credentials to /api/2.x/login and use x-auth-token header.",
        "auth_type": "token",
        "auth_hint": "Provide Purity admin user + password. Some deployments use API token via /api/2.x/login with an API token in the body.",
        "auth_defaults": {
            "login_path": "/api/2.26/login",
            "login_method": "POST",
            "username_field": "username",
            "password_field": "password",
            "token_path": "items.0.api_token",
            "token_header": "x-auth-token",
            "token_prefix": "",
        },
        "base_url_example": "https://flasharray.example.com",
        "color": "#FE5000",
        "endpoints": [
            {"name": "list_arrays", "method": "GET", "path": "/api/2.26/arrays",
             "description": "List FlashArray cluster info."},
            {"name": "list_volumes", "method": "GET", "path": "/api/2.26/volumes",
             "description": "List all volumes on the array.",
             "query_params": [
                 {"name": "limit", "description": "Max rows", "required": False},
             ]},
            {"name": "list_hosts", "method": "GET", "path": "/api/2.26/hosts",
             "description": "List hosts connected to the array."},
            {"name": "list_snapshots", "method": "GET", "path": "/api/2.26/volume-snapshots",
             "description": "List volume snapshots."},
            {"name": "array_performance", "method": "GET", "path": "/api/2.26/arrays/performance",
             "description": "Get array-level performance (IOPS, latency, bandwidth)."},
        ],
    },
]


def get_template(template_id: str) -> Dict | None:
    for t in TEMPLATES:
        if t["id"] == template_id:
            return t
    return None
